- name: App Install
  hosts: windows_servers
  tasks:
          - name: Install kubectl
            win_chocolatey:
                    name: kubernetes-cli
                    state: present

          - name: Install helm
            win_chocolatey:
                    name: kubernetes-helm
                    state: present

          - name: Install DotNetCore
            win_feature:
                    name: NET-Framework-Core
                    state: present

          - name: Install Powershell 7
            win_package:
                    path: C:\Softwares\PowerShell-7.2.2-win-x86.msi
                    state: present
                    
          - name: Install Docker Desktop
            win_chocolatey:
                    name: docker-desktop
                    state: present
              
          - name: Install Azure CLI
            win_chocolatey:
                    name: azure-cli
                    state: present
    
          - name: Install Notepad++
            win_chocolatey:
                    name: notepadpluplus
                    state: present